### ISSUE TITLE
Đề xuất thay đổi cách lưu địa chỉ

### ISSUE THREAD

**Issue by duong204736** [Duongneee/RentHouseBK#20]
Thay đổi cách lưu địa chỉ thành 3 trường trong bảng Posts:
``cityId``: ID cấp tỉnh/TP
``districtId``: ID cấp huyện/phường
``warnId``: ID cấp xã/phường
Xem thêm chi tiết tại file ``data.json`` trong repo: https://github.com/duong204736/DiaGioiHanhChinhVN
Mục đích: đơn giản hóa việc tìm kiếm và lọc bài đăng theo địa chỉ.

**Comment by Duongneee** [comment]
Nếu nó dễ dàng hơn thì nên đổi.

**Comment by duong204736** [comment]
Làm gần xong phần này thì nhận ra có hơi sai lầm: lưu tên thay vì id bởi id và tên không khác nhau nhiều về ý nghĩa mà khi ráp lại đc từ db sẽ đơn giản hơn nhiều. 
Sẽ thêm trường "street". Như vậy mỗi địa chỉ sẽ có 4 trường dữ liệu.
Vd: "Địa chỉ: 179 Đường Lê Đình Thám, Phường Tân Quý, Quận Tân Phú, Hồ Chí Minh"
gồm :
```
street: "179 Đường Lê Đình Thám", 
ward: "Phường Tân Quý", 
district: "Quận Tân Phú",
city: "Thành phố Hồ Chí Minh"
```
Một số địa chỉ sẽ không thể lưu được do đơn vị hành chính bị thay đổi trên thực tế
Vd: "Địa chỉ: 88 Phố Mai Hắc Đế, Phường Bùi Thị Xuân, Quận Hai Bà Trưng, Hà Nội"
gồm
```
street: "88 Phố Mai Hắc Đế", 
ward: "Phường Bùi Thị Xuân", 
district: "Quận Hai Bà",
city: "Hà Nội"
``` 
có Phường Bùi Thị Xuân đã bị đổi tên và sát . Trường hơp này vẫn lưu tên phường nhưng sẽ không được sử dụng cho tính năng lọc Posts theo địa chỉ.

**Comment by duong204736** [comment]
Fixxed in #24
